<a href="https://colab.research.google.com/github/davidoises-wpi/CS539_ML/blob/user%2Fdavidoises-wpi%2Fweek1/week1/lab_1-1-python-intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# LAB 1-1

This lab serves as a sanity check to ensure we have a baseline mastery of the fundamentals of Python.


**Submission**: Please do see the section entitled `TODO: PRACTICE EXERCISES` at the end for the actual exercises that you'll be submitting and how.



## Google Colaboratory (Google CoLab)


[Jupyter notebooks](https://jupyter.org/) are a standard tool for data scientists. They allow you to create and share documents that contain "cells" with runnable Python code as well as equations, visualizations, and text. [Google Colab](http://colab.research.google.com/) gives you the same ability online in a collaborative environment with all the resources of a powerful virtual machine underlying the notebook execution.

Here is [an overview of Google Colaboratory (Google CoLab) features](https://colab.research.google.com/notebooks/basic_features_overview.ipynb) and a brief guide for [using BigQuery through Colaboratory](https://colab.research.google.com/notebooks/bigquery.ipynb). Before proceeding, make sure you have read and understood these support documents. To open a new notebook in [Colab](http://colab.research.google.com/), you can go to *File \> Upload notebook* and choose the file either from your computer or from Google Drive. You can also make a copy of an existing Colab noteboook by going to *File \> Save a Copy in Drive ...* . Colab notebooks can be saved just like any other file to your own Google Drive account.



# INTRODUCTION TO PYTHON

Welcome to our introduction to the Python Programming Language using our first iPython Notebook on Google CoLab!

# Variables

We use variables to represent locations in computer memory where we store data for our program. To initialize variables in a Python program, you simply type the variable name followed by an equals sign and then some expression that evaluates to the variable's initial value. Here are some examples:

In [ ]:
x = 2
mass = 12.3
speed_of_light = 299792458
energy = mass * (speed_of_light ** 2)
raining = True
course_csc1500 = "Computer Science 1"
energy, raining, course_csc1500

Variable names must start with a letter or an underscore, followed by any sequence of letters, digits and underscores. Variables are case-sensitive, so the variables `salary` and `Salary` are different. Variable names cannot include spaces.

The instructions above are called *assignment statements* since they assign a value to a variable. All assignment statements have a single variable followed by an equals sign followed by either a data value or an computation (expression) contains variables and/or data values. For numerical computations, here are the operators you can use:

In [ ]:
+   addition
-   subtraction
*   multiplication
/   division
//      truncated division
%   remainder (think: modulo)
**  exponentiation

NB: In 2.7,  `/` behaves like `//`

When you type expressions with more than one arithmetic operator, they are evaluated based on the usual mathematical *precedence*, with exponentiation performed first, then multiplication, division and remainder next, and finally addition and subtraction last. If there is more than one operator of the same type (e.g. addition and subtraction), they are evaluated left to right. If you want to force a lower precedence operation to be performed first, use parentheses like you would in ordinary mathematics. For example, here is a Python statement that computes the total amount due for a loan using simple interest given the principal (amount borrowed), interest rate per month and time of loan in months:

In [ ]:
total_amount = principal * (1 + rate * time)

# Input and Output

If you want to input numerical data into your program from the keyboard, you can use the `input` function:

In [ ]:
tempF = int(input("Input the temperature in Fahrenheit: "))

The `input` function requires a string that is output to prompt the user with an instruction on what input is required. The `int()` typecast converst the input string to integer. The numerical value the user types in is then stored in the variable `tempF`.

NB: In 2.7, you don't need the `int()`

To output the value of a variable or expression, you simply use the `print` function. Here are three examples:

In [ ]:
print("The temperature in Fahrenheit: ")
print(tempF)
print("The temperature in Celsius is ", (5.0/9.0)*(tempF - 32.0))
print(mass, " * ", speed_of_light, " ** 2 = ", energy)

NB: In 2.7, you don't need the parentheses after a function name/identifier

In the first two examples, there is only one item being printed per line. In the last two examples, more than one item is printed on the same line.

# Writing Python Programs

A simple Python program has the following format:

In [ ]:
def main():
    ---------------------------
    Python instructions go here
    ---------------------------
        <-- blank line here
main()

The instructions of the program are stored in the function definition (`def`) named `main`. The final instruction runs the `main` function it is defined. Here is an example of a short program that converts an input temperature in Fahrenheit to Celsius:

In [ ]:
def main():
       tempF = int(input("Input the temperature in Fahrenheit: "))
       tempC = (5.0/9.0) * (tempF - 32.0)
       print(tempF, " F = ", tempC, " C")
main()

Note that the instructions in the `main` function definition are all indented. We suggest you use one tab to line up all instructions in `main`.

# Loops

If you want to repeat instructions a specific number of times, you can use the `for` instruction:

In [ ]:
    for i in range(10):
        print(i)


The loop above sets i to values in the range from 0 up to *but not including* 10. Another way to look at it is that it is a loop that repeats exactly 10 times. Here is the output:

In [ ]:
0
1
2
3
4
5
6
7
8
9

Here is a slightly different version. Notice the extra comma at the end of the `print` statement:

In [ ]:
    for i in range(10):
        # In 2.7, you could do this: print i,
        print(i,end=' ')

Since the `print` statement has a comma, the cursor stays on the same line to print the next item. Here is the new output:

In [ ]:
0 1 2 3 4 5 6 7 8 9

Notice that the instruction that is repeated is indented below the `for` instruction. A loop can repeat more than one instruction, as a group, as shown below:

In [ ]:
    for i in range(10):
        print(i, "\t",end=' ')
        print(i**2, "\t",end=' ')
        print(i**3)


The loop consists of a block or set of 3 instructions that are repeated 10 times. This loop prints out a table of the squares and cubes of the integers 0 through 9. The "\\t" string is a special symbol for one press of the tab key on the keyboard. The extra comma at the end of the first two `print` statements keeps the cursor on the same line until we get to the third `print` statement. The instruction(s) that repeat in a loop is called the *loop body*. Here is the output:

In [ ]:
0   0   0
1   1   1
2   4   8
3   9   27
4   16  64
5   25  125
6   36  216
7   49  343
8   64  512
9   81  729

Sometimes you might have a computation that you have to repeat, but you don't know specifically how many times you must repeat the computation. You can use the `while` loop to handle this. Based on the condition you give, the loop will repeat as long as the condition holds. For example, let's say you want to print your table above until the cube value exceeds 500. Here's how we would write this:

In [ ]:
    i = 0
    while i**3 < 500:
        print(i, "\t",end=' ')
        print(i**2, "\t",end=' ')
        print(i**3)
        i = i + 1


Note that we have to initialize `i` explicitly here before the loop begins, and we have to add 1 to `i` before we start our next iteration of the loop. (The `for` loop you saw above does this automatically, but the `while` loop has more flexibility and can run an arbitrary number of times.) Here is the output this time:

In [ ]:
0   0   0
1   1   1
2   4   8
3   9   27
4   16  64
5   25  125
6   36  216
7   49  343

Here are the operators you can use to compare one value to another for the condition of a `while` loop:

In [ ]:
<   is less than
>   is greater than
==  is equal to
<=  is less than or equal to
>=  is greater than or equal to
!=  is not equal to

The operators above are called *relational operators* since they allow you to determine the relation of one value to another.

As a final example, here is a Python program to compute the GCD of two integers:

In [ ]:
    # gcd.py
    # Program to compute GCD

    def main():
        x = int(input("Input the first integer: "))
        y = int(input("Input the second integer: "))
        print("The GCD of ", x, " and ", y, " is ",end=' ')
        while y != 0:
            x_prime = y
            y_prime = x % y
            x = x_prime
            y = y_prime
        print(x)

    main()

The program asks for values for `x` and `y`, then repeats the set of 4 instructions of the `while` loop while y is not equal to 0, and finally outputs the final value of `x` as the answer for the GCD calculation. The symbol `#` represents a *comment* which just a message for us to explain the purpose of the program. The text after the `#` on each line is ignored by the Python interpreter.

# Dictionaries

We can setup dictionaries as key:value pairs of values. A dictionary is an unordered collection of data values that is used to store data values like a map. We can create a dictionary as so:

In [ ]:
    d = {1: 10, 2: 20, 3: 30, 4: 40, 5: 50, 6: 60}


We can then check if a particular key is in the dictionary as so:

In [ ]:
    if 3 in d:
      print("3 is in d!")


The key in a dictionary can be any immutable type. We can thus declare more complex dictionaries like:

In [ ]:
    d = {'x': 10, 'y': 20, 'z': 30}
    for dict_key, dict_value in d.items():
        print(dict_key,'->',dict_value)


We can also pull just the keys and sort the keys and then use the key to get the value, as follows:

In [ ]:
    color_dict = {'red':'#FF0000',
                  'green':'#008000',
                  'black':'#000000',
                  'white':'#FFFFFF'
                 }

    for key in sorted(color_dict):
        print("%s: %s" % (key, color_dict[key]))

In fact, we can also setup a dictionary of dictionaries and process it as follows to remove duplicate values:

In [ ]:
    student_data = {'id1':
       {'name': ['Sara'],
        'class': ['V'],
        'subject_integration': ['english, math, science']
       },
     'id2':
      {'name': ['David'],
        'class': ['V'],
        'subject_integration': ['english, math, science']
       },
     'id3':
        {'name': ['Sara'],
        'class': ['V'],
        'subject_integration': ['english, math, science']
       },
     'id4':
       {'name': ['Surya'],
        'class': ['V'],
        'subject_integration': ['english, math, science']
       },
    }

    result = {}

    for key,value in student_data.items():
        if value not in result.values():
            result[key] = value

    print(result)

We can use the dictionary data structure for sparse datasets as you only need to represent the non-trival values here. Here is a link to [lists, tuples, and dictionaries](http://sthurlow.com/python/lesson06/) and one with some [Python Tricks](http://www.petercollingridge.co.uk/book/export/html/362).

# List Comprehensions

List comprehensions are a very powerful construct in Python that is based on the [set-builder
notation](https://www.quora.com/Why-are-%E2%80%9Clist-comprehensions%E2%80%9D-called-%E2%80%9Clist-comprehensions%E2%80%9D-in-Python-They-seem-more-like-%E2%80%9Clist-builders%E2%80%9D) in mathematics, which are also called **set comprehensions** or **set abstractions**. Set comprehensions in mathematics can be used to build a set as below, for example:

${𝑥 | 𝑥 \in \{1,\dots,100\} \wedge 𝑥 \mod 2 = 0}$

This can be expressed in Python in a similar way:

In [ ]:
[x for x in range(1,101) if x % 2 == 0]

This isn't limited to purely mathematical constructs, of course; e.g., consider this set-builder:

`{ x: x is a whole number less than 20, x is even }`

An equivalent set can be expressed in Python as:

In [ ]:
[x for x in 'MATHEMATICS' if x in ['A','E','I','O','U']]

We can also use this approach to make dictionary comprehensions, for example. I'd also highly recommend looking at list comprehensions as shown in this link, [List Comprehensions visualized](http://treyhunner.com/2015/12/python-list-comprehensions-now-in-color/), as they're a very handy compact representation of `for-loop` constructs although we'll usually favour the old-fashioned, more familiar and readable approach for the most part.

# Functions

Try and predict what each of the following cells will output when you press the Play button in the following cells.

**Nota Bene**: the `1, 2, 3` in the left part are the line numbers and not part of the Python code.

In [ ]:
x = 1
y = 2
x + y
y

`add_numbers()` is a function that takes two numbers and adds them together.

In [ ]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

`add_numbers()` updated to take an optional 3rd parameter. Using `print()` allows printing of multiple expressions within a single cell.

In [ ]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

`add_numbers()` updated to take an optional flag parameter.

In [ ]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z

print(add_numbers(1, 2, flag=True))

Assign function `add_numbers` to variable `a`.

In [ ]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

# Types and Sequences

Use `type` to return the object's type.

In [ ]:
type('This is a string')
type(None)
type(1)
type(1.0)
type(add_numbers)

Tuples are an immutable data structure (cannot be altered).

In [ ]:
x = (1, 'a', 2, 'b')
type(x)

Lists are a mutable data structure.

In [ ]:
x = [1, 'a', 2, 'b']
type(x)

Use `append` to append an object to a list.

In [ ]:
x.append(3.3)
print(x)

This is an example of how to loop through each item in the list.

In [ ]:
for item in x:
    print(item)

Or using the indexing operator:

In [ ]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

Use `+` to concatenate lists.

In [ ]:
[1,2] + [3,4]

Use `*` to repeat lists.

In [ ]:
[1]*3

Use the `in` operator to check if something is inside a list.

In [ ]:
1 in [1, 2, 3]

Now let's look at strings. Use bracket notation to slice a string.

In [ ]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters

This will return the last element of the string.

In [ ]:
x[-1]

This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [ ]:
x[-4:-2]

This is a slice from the beginning of the string and stopping before the 3rd element.

In [ ]:
x[:3]

And this is a slice starting from the 3rd element of the string and going all the way to the end.

In [ ]:
x[3:]

In [ ]:
firstname = 'Gary'
lastname = 'Kildall'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Gary' in firstname)

`split` returns a list of all the words in a string, or a list split on a specific character.

In [ ]:
firstname = 'Gary Arlen Kildall'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Gary Arlen Kildall'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Make sure you convert objects to strings before concatenating.

In [ ]:
'Gary' + 2
'Gary' + str(2)

Dictionaries associate keys with values.

In [ ]:
x = {'Gary Kildall': 'gkildall@digitalresearch.com', 'Bill Gates': 'billg@microsoft.com'}
x['Gary Kildall'] # Retrieve a value by using the indexing operator

In [ ]:
x['Steve Jobs'] = None
x['Steve Jobs']

Iterate over all of the keys:

In [ ]:
for name in x:
    print(x[name])

Iterate over all of the values:

In [ ]:
for email in x.values():
    print(email)

Iterate over all of the items in the list:

In [ ]:
for name, email in x.items():
    print(name)
    print(email)

You can unpack a sequence into different variables:

In [ ]:
x = ('Gary', 'Kildall', 'gkildall@digitalresearch.com')
fname, lname, email = x
fname
lname

Make sure the number of values you are unpacking matches the number of variables
being assigned.

In [ ]:
x = ('Gary', 'Kildall', 'gkildall@digitalresearch.com', 'Digital Research')
fname, lname, email = x

# More on Strings

In [ ]:
print('Gary' + 2)

In [ ]:
print('Gary' + str(2))

Python has a built in method for convenient string formatting.

In [ ]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Gary'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

# Reading and Writing CSV files

Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [24]:
import csv

%precision 2

with open('week1/tutorials_1-1-python-mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

mpg[:3] # The first three dictionaries in our list.

[{'': '1',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'auto(l5)',
  'drv': 'f',
  'cty': '18',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '2',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '1.8',
  'year': '1999',
  'cyl': '4',
  'trans': 'manual(m5)',
  'drv': 'f',
  'cty': '21',
  'hwy': '29',
  'fl': 'p',
  'class': 'compact'},
 {'': '3',
  'manufacturer': 'audi',
  'model': 'a4',
  'displ': '2',
  'year': '2008',
  'cyl': '4',
  'trans': 'manual(m6)',
  'drv': 'f',
  'cty': '20',
  'hwy': '31',
  'fl': 'p',
  'class': 'compact'}]

`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 234 dictionaries.

In [8]:
len(mpg)

234

`keys` gives us the column names of our csv.

In [25]:
mpg[0].keys()

dict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])

This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

In [26]:
sum(float(d['cty']) for d in mpg) / len(mpg)

16.86

Similarly this is how to find the average hwy fuel economy across all cars.

In [27]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

23.44

Use `set` to return the unique values for the number of cylinders the cars in our dataset have.

In [28]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

{'4', '5', '6', '8'}

Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.

In [32]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

Use `set` to return the unique values for the class types in our dataset.

In [33]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

{'2seater', 'compact', 'midsize', 'minivan', 'pickup', 'subcompact', 'suv'}

And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [34]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the class type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

# Dates and Times

In [35]:
import datetime as dt
import time as tm

`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [36]:
tm.time()

1705006739.96

Convert the timestamp to datetime.

In [37]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

datetime.datetime(2024, 1, 11, 20, 59, 1, 427929)

Handy datetime attributes:

In [38]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2024, 1, 11, 20, 59, 1)

`timedelta` is a duration expressing the difference between two dates.

In [39]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(days=100)

`date.today` returns the current local date.

In [40]:
today = dt.date.today()
today - delta # the date 100 days ago
today > today-delta # compare dates

True

# Objects and map()

An example of a class in python:

In [41]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [42]:
person = Person()
person.set_name('Gary Kildall')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Gary Kildall live in Ann Arbor, MI, USA and works in the department School of Information


Here's an example of mapping the `min` function between two lists.

In [43]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

Now let's iterate through the map object to see the values.

In [44]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


# Lambda and List Comprehensions


Here's an example of lambda that takes in three parameters and adds the first two.

In [45]:
my_function = lambda a, b, c : a + b
my_function(1, 2, 3)

3

Let's iterate from 0 to 999 and return the even numbers.

In [46]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

Now the same thing but with list comprehension.

In [47]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

# Numerical Python (NumPy)

In [48]:
import numpy as np

## Creating Arrays

Create a list and convert it to a numpy array

In [49]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

Or just pass in a list directly

In [50]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

Pass in a list of lists to create a multidimensional array.

In [51]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

Use the shape method to find the dimensions of the array. (rows, columns)

In [52]:
m.shape

(2, 3)

`arange` returns evenly spaced values within a given interval.

In [53]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

`reshape` returns an array with the same data with a new shape.

In [54]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

`linspace` returns evenly spaced numbers over a specified interval.

In [55]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

`resize` changes the shape and size of array in-place.

In [56]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

`ones` returns a new array of given shape and type, filled with ones.

In [57]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

`zeros` returns a new array of given shape and type, filled with zeros.

In [58]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

`diag` extracts a diagonal or constructs a diagonal array.

In [60]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

Create an array using repeating list (or see `np.tile`)

In [61]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

Repeat elements of an array using `repeat`.

In [62]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

### Combining Arrays

In [66]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

Use `vstack` to stack arrays in sequence vertically (row wise).

In [64]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

Use `hstack` to stack arrays in sequence horizontally (column wise).

In [65]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [ ]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

**Dot Product:**

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [72]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6
y
z = np.array([y, y**2])
z
print(len(z)) # number of rows of array

2


Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [73]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

The shape of array `z` is `(2,3)` before transposing.

In [74]:
z.shape

(2, 3)

Use `.T` to get the transpose.

In [75]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

The number of rows has swapped with the number of columns.

In [76]:
z.T.shape

(3, 2)

Use `.dtype` to see the data type of the elements in the array.

In [77]:
z.dtype

dtype('int64')

Use `.astype` to cast to a specific type.

In [78]:
z = z.astype('f')
z.dtype

dtype('float32')

## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [79]:
a = np.array([-4, -2, 1, 3, 5])
a.sum()
a.max()
a.min()
a.mean()
a.std()

3.2619012860600183

`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [80]:
a.argmax()
a.argmin()

0

## Indexing / Slicing

In [81]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [82]:
s[0], s[4], s[-1]

(0, 16, 144)

Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [83]:
s[1:5]

array([ 1,  4,  9, 16])

Use negatives to count from the back.

In [84]:
s[-4:]

array([ 81, 100, 121, 144])

A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [85]:
s[-5::-2]

array([64, 36, 16,  4,  0])

Let's look at a multidimensional array.

In [86]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Use bracket notation to slice: `array[row, column]`

In [87]:
r[2, 2]

14

And use : to select a range of rows or columns

In [88]:
r[3, 3:6]

array([21, 22, 23])

Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [ ]:
r[:2, :-1]

This is a slice of the last row, and only every other element.

In [ ]:
r[-1, ::2]

We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [89]:
r[r > 30]

array([31, 32, 33, 34, 35])

Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [90]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [91]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

Set this slice's values to zero ([:] selects the entire array)

In [92]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

`r` has also been changed!

In [93]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

To avoid this, use `r.copy` to create a copy that will not affect the original array

In [94]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

Now when r_copy is modified, r will not be changed.

In [95]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [96]:
test = np.random.randint(0, 10, (4,3))
test

array([[5, 6, 1],
       [7, 7, 8],
       [1, 5, 3],
       [0, 6, 8]])

Iterate by row:

In [97]:
for row in test:
    print(row)

[5 6 1]
[7 7 8]
[1 5 3]
[0 6 8]


Iterate by index:

In [100]:
for i in range(len(test)):
    print(test[i])

[5 6 1]
[7 7 8]
[1 5 3]
[0 6 8]


Iterate by row and index:

In [101]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [5 6 1]
row 1 is [7 7 8]
row 2 is [1 5 3]
row 3 is [0 6 8]


Use `zip` to iterate over multiple iterables.

In [102]:
test2 = test**2
test2

array([[25, 36,  1],
       [49, 49, 64],
       [ 1, 25,  9],
       [ 0, 36, 64]])

In [103]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[5 6 1] + [25 36  1] = [30 42  2]
[7 7 8] + [49 49 64] = [56 56 72]
[1 5 3] + [ 1 25  9] = [ 2 30 12]
[0 6 8] + [ 0 36 64] = [ 0 42 72]


# TODO: PRACTICE EXERCISES


Please fill in your answers in the following code and text cells, <u>including comments</u> as needed. The area to enter your answers is indicated by ellipses (`...`) below. For all code developed, please be sure to add <u>explanatory comments</u> to encapsulate your understanding.

Then, please submit both the `.ipynb` file and the `.pdf` file, as per the Submission Instructions below.

In [ ]:
...

## Exercise 1

Write and run a Python program that asks the user for a temperature in Celsius and converts and outputs the temperature in Fahrenheit.  (Use the formula given in the example above and solve for `tempF` in terms of `tempC`.)

In [150]:
# Main function
def main():
    # Get temp c as input from user
    tempC = int(input("Input the temperature in Celsius: "))

    # Convert to F
    tempF = (tempC * 9.0/5.0) + 32.0

    # Print result
    print(tempC, " C = ", tempF, " F")

# Execute
main()

Input the temperature in Celsius: 25
25  C =  77.0  F


## Exercise 2

Here is an algorithm to print out n! (n factorial) from 0! to 19!:

In [ ]:
1. Set f = 1
2. Set n = 0
3. Repeat the following 20 times: # range(20) will repeate 20 times although range(1,20) will also work with 1 fewer runs due to the base case
   a. Output n, "! = ", f
   b. Add 1 to n
   c. Multiply f by n

Using a `for` loop, write and run a Python program for this algorithm.

In [151]:
# Factorial of 0
f = 1

# Print 0! since it is out of the loop
print("0! = ", f)

# Iterate 1...19
for n in range(1,20):

  # f = n! = n*(n-1)!
  f = f*n

  # print result of n!
  print(n, "! = ", f)

0! =  1
1 ! =  1
2 ! =  2
3 ! =  6
4 ! =  24
5 ! =  120
6 ! =  720
7 ! =  5040
8 ! =  40320
9 ! =  362880
10 ! =  3628800
11 ! =  39916800
12 ! =  479001600
13 ! =  6227020800
14 ! =  87178291200
15 ! =  1307674368000
16 ! =  20922789888000
17 ! =  355687428096000
18 ! =  6402373705728000
19 ! =  121645100408832000


## Exercise 3

Modify the program above using a `while` loop so it prints out all of the factorial values that are _less than 1 billion_. (You should be able to do this without looking at the output of the previous exercise.)

In [152]:
# Initialize n to 0 and f to n!
f = 1
n = 0

# Infinite loop
while True:

  # Display factorial
  print(n, "! = ", f)

  # Increment n and calctulate n! = n*(n-1)!
  n = n +1
  f = f*n

  # Stop the infinite loop if factorial is > 1 billion
  if f >= 1.0e9:
    break

0 ! =  1
1 ! =  1
2 ! =  2
3 ! =  6
4 ! =  24
5 ! =  120
6 ! =  720
7 ! =  5040
8 ! =  40320
9 ! =  362880
10 ! =  3628800
11 ! =  39916800
12 ! =  479001600


## Exercise 4

Repeat #3 above using list comprehensions. Please see these increasingly more sophisticated references for list comprehensions:

* [Simple](http://www.pythonforbeginners.com/basics/list-comprehensions-in-python)
* [Advanced](https://web.archive.org/web/20171126231647/http://www.secnetix.de/olli/Python/list_comprehensions.hawk)
* [Complex](http://www.python-course.eu/list_comprehension.php) (has a hint for this problem).



In [153]:
# Empty list
s = []

# 1. Iterates through 1...19
# 2. Factorial is calculated as f = x*s[-1], if s doesnt exist then it is f = x*1
# 3. If f is less than 1 billion then append f to s. Trick: putting "not s.append()" as a condition allows the comprehension to execute the append
# 4. The current iteration appended f to the end of the list and returns s[-1] which is the factorial
s = [s[-1] for x in range(1,20) if x*(s[-1] if s else 1) < 1.0e9 and not s.append(x*(s[-1] if s else 1))]

# Add the factorial of 0 to the beginning of the list
s = [1] + s

# Iterate through factorial list and print results
_ = [print(i, "! = ",x) for i,x in enumerate(s)]


0 ! =  1
1 ! =  1
2 ! =  2
3 ! =  6
4 ! =  24
5 ! =  120
6 ! =  720
7 ! =  5040
8 ! =  40320
9 ! =  362880
10 ! =  3628800
11 ! =  39916800
12 ! =  479001600


## Exercise 5

Suppose you have a dictionary of dictionaries, or a 2D dictionary, called `banditos` as follows:

In [154]:
alonzo = {"age": 10, "height": 42, "weight": 175, "instrument":"fiddle" }
turing = {"age": 41, "height": 70, "weight": 160, "instrument":"theremin"}
bertha = {"age": 32, "height": 97, "weight": 587, "instrument":"cello"}
tinkerB = {"age":100, "height": 4, "weight": 0.5, "instrument":"cello"}
banditos = {"Alonzo": alonzo, "Turing": turing, "Bertha": bertha, "TinkerB": tinkerB}


We can access the sub-dictionary, or vector, of Alonzo's attributes as follows:

In [155]:
banditos["Alonzo"]


{'age': 10, 'height': 42, 'weight': 175, 'instrument': 'fiddle'}

We can also return a specific feature of Alonzo's as:

In [156]:
banditos["Alonzo"]["age"]


10

For the above dictionary, `banditos`, write a function that, when given the dictionary, returns a list of users who play a certain instrument. E.g., here's a sample run and its result:

In [ ]:
find_players(banditos, "cello")

  ['Bertha', 'TinkerB']

In [160]:
def find_players(players_data, instrument):
  # Iterate through the keys and values (players and features)
  # If the current player's instrument matches then add player to the list
  return [player for player,features in players_data.items() if features["instrument"] == instrument]

find_players(banditos, "cello")


['Bertha', 'TinkerB']

# Submission Instructions

Once you have filled out the Colab notebook completely, you are ready to submit. Your final submission will consist of the `.ipynb` and the `.pdf` files, as described below:

1. Download the Google Colab notebook as an iPython notebook
   * You can do this by going to *File \> Download .ipynb*
2. Print out a PDF of your Colab notebook.
   * In Google Chrome, you can do this by going to *File \> Print* and then
choosing *Save to PDF*.
   * **Make sure you have run all cells first.**
   * Ensure you've closed the table of contents sidebar before you print so we can easily see your work and output.
3. Submit **both** the `.ipynb` notebook and the `.pdf` files via Blackboard or directly via the cloud using the Google Integration with Blackboard (if applicable).

---